[project]
name = "open-db-phm"
version = "0.1.0"
description = "Open Database for Predictive Health Monitoring (PHM)"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "pandas-stubs==2.3.2.250926",
    "pandas>=2.3.1",
    "requests>=2.32.4",
    "isatools>=0.11.0",
]
